repos:
  -   repo: https://github.com/ambv/black
      rev: stable
      hooks:
        - id: black
          language_version: python3.7
  -   repo: https://github.com/PyCQA/flake8
      rev: 3.9.0
      hooks:
      -   id: flake8
          additional_dependencies: [flake8-typing-imports==1.7.0, flake8-import-order==0.18.1,flake8-tidy-imports==4.2.1]
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-docstring-first
        -   id: debug-statements
        -   id: requirements-txt-fixer
        -   id: check-merge-conflict
  -   repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.5.6
      hooks:
      -   id: autopep8

  -   repo: local
      hooks:
        - id: django-test
          name: django-test
          entry: python manage.py test
          always_run: true
          pass_filenames: false
          language: system
